---
abstract: 'Base58 encodings with BigInt'
author:
  - 'cho45 <cho45@lowreal.net>'
build_requires:
  ExtUtils::MakeMaker: 6.36
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Encode-Base58-BigInt
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Exporter::Lite: 0
  Filter::Util::Call: 0
  Math::BigInt: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/cho45/Encode-Base58-BigInt.git
version: 0.03
